<div class="header-ree-interna">
    <div class="box-title">
        <h2 class="tit-ree">Términos de uso</h2>
    </div>
</div>

<div class="container container-ree">
    <h3>TÉRMINOS DE ACEPTACIÓN</h3>
    <p>Reelance pone a disposición para su uso en este sitio web información, documentos y productos , sujetos a los términos y condiciones establecidos anteriormente en este documento (los “Términos de Uso”). Al acceder o usar esta web, lo cual incluye su acceso o el uso de cualquiera de los Servicios, usted se muestra de acuerdo con los Términos de Uso. Reelance se reserva el derecho de cambiar los Términos de Uso a su entera discreción. Su uso de la web estará sujeto a la versión más reciente de los Términos de Uso que esté expuesta en dicha web en el momento del uso. También, cuando se usen Servicios particulares o Materiales de esta web, deberá ceñirse a cualquier indicación o regla aplicable a los Servicios o Materiales involucrados que puedan contener términos y condiciones, además de los descritos en los Términos de Uso. Todas estas indicaciones y reglas son, por medio de la presente, incorporadas como referencia en los Términos de Uso. Si usted no respeta alguno de los Términos de Uso, su autorización para usar esta web termina automáticamente y debe destruir inmediatamente cualquier Material descargado o impreso obtenido en esta web.</p>
    <h3>PROPIEDAD INTELECTUAL</h3>
    <p>La información de Marca Registrada, las Marcas Registradas y las Marcas de Servicio (“Marks”) que se muestran en el sitio web son propiedad de Reelance. Se prohíbe el uso de dichas marcas sin el consentimiento previo y escrito de Reelance. Reelance y el logo de Reelance son Marcas Registradas de Reelance Lab. Co.</p>
    <p>Los Materiales y los Servicios de esta web están protegidos por las leyes del Copyright y /o otras leyes de la propiedad intelectual y cualquier uso no autorizado de estos Materiales o Servicios puede violar dichas leyes. Excepto como se describe en este documento, Reelance y sus proveedores no le conceden a usted ningún derecho implícito o explícito bajo cualquier patente, copyright, marca registrada o información secreta con respecto a las Formulas y Servicios.</p>
    <p>El uso de los servicios o la descarga de cualquier otra adquisición de cualquier material a través de la web, se realiza a su propia discreción y riesgo y bajo el acuerdo de que usted será el responsable único y final de cualquier daño o pérdida de datos en su computadora derivado/a de dichas actividades. Ningún consejo o información, ya sea oral o escrita, obtenida por usted de Reelance o a través o desde la web, puede crear cualquier tipo de garantía no expresamente descrita en los Términos de Uso</p>
    <p>Mediante envío por su parte de cualquier información, ideas, conceptos o técnicas (Feedback) a Reelance, usted asume que: (i) Dicho feedback no contiene ningún material confidencial ni registrado; (ii) Reelance no está obligado a tratar el feedback confidencialmente, expresa ni implícitamente; (iii) Reelance se reserva la potestad de usar o desechar cualquier contenido feedback con cualquier propósito y en cualquier parte del mundo, así como localmente para su único beneficio; (iv) Su feedback pasará a ser propiedad de Reelance sin que ello signifique ningún tipo de obligación por parte de Reelance para con usted; y (v) usted no tendrá ningún derecho a ser compensado de ningún modo por ello.</p>
    <h3>GARANTÍA Y LIMITACIÓN DE RESPONSABILIDAD</h3>
    <p>EXCEPTO BAJO LA EXPRESA AUTORIZACIÓN POR ESCRITO DE REELANCE, TODOS LOS MATERIALES Y SERVICIOS DE ESTA WEB SON PROVEÍDOS “TAL CUAL”, SIN GARANTÍA DE CUALQUIER TIPO, YA SEA EXPRESA O IMPLÍCITA, INCLUYENDO, PERO NO LIMITÁNDOSE A, LAS GARANTÍAS DE COMERCIALIZACIÓN O IDONEIDAD PARA UN PROPÓSITO PARTICULAR, O LA GARANTÍA DE NO INFRACCIÓN. SIN LIMITAR LO ANTERIORMENTE DICHO, REELANCE NO OFRECE GARANTÍA DE QUE (I) LOS SERVICIOS Y MATERIALES CUBRIRÁN SUS NECESIDADES, (I.E.) LOS SERVICIOS Y MATERIALES SERÁN ININTERRUMPIDOS, OPORTUNOS, SEGUROS O LIBRES DE ERRORES. (I.E.) LOS RESULTADOS QUE PUEDEN SER OBTENIDOS DEL USO DE ESTOS SERVICIOS O MATERIALES SERÁN EFECTIVOS, PRECISOS O FIABLES, (I.E.) LA CALIDAD DE LOS PRODUCTOS, SERVICIOS O LA INFORMACIÓN COMPRADA U OBTENIDA POR USTED A TRAVÉS DE LA WEB ESTARÁ COINCIDIRÁ CON SUS EXPECTATIVAS Y (V) CUALQUIER ERROR EN EL PRODUCTO OBTENIDO DEL SITIO SERÁ CORREGIDO. EN ALGUNOS ESTADOS O JURISDICCIONES LA DURACIÓN DE LA GARANTÍA IMPLÍCITA PUEDE VARIAR. ASÍ PUES, LAS LIMITACIONES DESCRITAS PUEDEN NO SER APLICABLES A USTED. EN LA MEDIDA DE LO POSIBLE, CUALQUIER GARANTÍA IMPLÍCITA ESTÁ LIMITADA A NOVENTA (90) DÍAS. ESTA WEB PODRÍA INCLUIR ERRORES TÉCNICOS O DE OTRO TIPO, INEXACTITUDES O ERRORES TIPOGRÁFICOS. REELANCE PUEDE CAMBIAR LOS MATERIALES Y SERVICIOS DE ESTA WEB, INCLUYENDO LOS PRECIOS Y LAS DESCRIPCIONES DE CUALQUIERA DE LOS PRODUCTOS LISTADOS EN CUALQUIER MOMENTO SIN PREVIO AVISO. EN NINGÚN CASO PODRÁN REELANCE O SUS PROVEEDORES SER RESPONSABLES ANTE CUALQUIER INCIDENTE O DAÑO ESPECIAL, PUNITIVO, INDIRECTO O CONSECUENTE NI DE TIPO ALGUNO, INCLUYENDO SIN LIMITACIÓN, AQUELLOS RESULTANTES DE LA PÉRDIDA DEL PRODUCTO O LOS BENEFICIOS, INDEPENDIENTEMENTE DE QUE REELANCE HAYA SIDO AVISADA DE LA POSIBILIDAD DE DICHOS DAÑOS Y EN CUALQUIER HIPÓTESIS DE RESPONSABILIDAD EMANANTE DE O EN CONEXIÓN CON EL USO DE ESTA WEB.</p>
    <p>Reelance no asume responsabilidad alguna por errores en la información, los productos, los materiales y/o los servicios a los que se hace referencia desde o hacia esta web. Las referencias a otras corporaciones, sus servicios y productos se proveen “tal cual”, sin garantía de cualquier tipo, ya sea expresa o implícita.</p>
    <p>El uso de los servicios o la descarga de cualquier otra adquisición de cualquier material a través de la web, se realiza a su propia discreción y riesgo y bajo el acuerdo de que usted será el responsable único y final de cualquier daño o pérdida de datos en su computadora derivado/a de dichas actividades. Ningún consejo o información, ya sea oral o escrita, obtenida por usted de Reelance o a través o desde la web, puede crear cualquier tipo de garantía no expresamente descrita en los Términos de Uso.</p>
    <p>Esta web contiene enlaces a las páginas web de terceras partes que no están bajo el control de Reelance. Reelance no actúa en representación de ninguna de estas páginas o partes. Así pues, cuando usted accede a un sitio web no perteneciente a Reelance, usted lo hace bajo su propia responsabilidad y riesgo y Reelance no es responsable de la exactitud o fiabilidad de cualquier información dato, opiniones, consejos o afirmaciones expuestas en dichos sitios web. Reelance provee esos enlaces meramente para la comodidad del usuario y la inclusión de dichos enlaces no implica que Reelance apoye o acepte responsabilidad alguna acerca del contenido o usos de las citadas webs. Se puede acceder a esta Web desde otros países a lo ancho del mundo y puede contener referencias a los productos de Reelance y servicios que no han sido anunciados en su país. Esas referencias no implican que Reelance tenga intención de anunciar / comercializar dichos productos, servicios o programas en su país.</p>
    <h3>INDEMNIZACIÓN</h3>
    <p>Usted acuerda indemnizar y liberar a Reelance y a sus subsidiarios, afiliados , oficiales, agentes, colaboradores y otras partes, así como empleados de cualquier responsabilidad o reclamación, incluyendo los honorarios razonables de un notario, invertidos por cualquier tercera parte a causa del contenido que usted envíe o transmita a través de la web (incluyendo sin limitación cualquier Contenido del Usuario), su uso de la web, su conexión a la web, su violación de los Términos de Uso o su violación de cualquier derecho de otra persona o entidad.</p>
</div>